/* eslint-env node */
module.exports = {
  swDest: 'service-worker.js',
  importWorkboxFrom: 'cdn',
  skipWaiting: false,
  clientsClaim: true,
  offlineGoogleAnalytics: true,
  cleanupOutdatedCaches: true,
  cacheId: 'BLOG-PWA',
  globDirectory: '.',
  globPatterns: [
    'index.html',
    'manifest.json',
    'src/components/page-view-element.js',
    'src/components/snack-bar.js',
    'src/components/ts-app.js',
    'src/components/ts-article.js',
    'src/components/ts-blog.js',
    'src/components/ts-home.js',
    'src/components/ts-care.js',
    'src/components/ts-contact.js',
    'src/components/ts-design.js',
    'src/components/ts-emergency.js',
    'src/components/ts-icons.js',
    'src/components/ts-image.js',
    'src/components/ts-item.js',
    'src/components/ts-migrations.js',
    'src/components/ts-offline.js',
    'src/components/ts-pagespeed.js',
    'src/components/ts-privacy.js',
    'src/components/ts-security.js',
    'src/components/ts-sidebar-nav.js',
    'src/components/ts-social.js',
    'src/components/ts-style-button.js',
    'src/components/ts-style-card.js',
    'src/components/ts-style-checkbox.js',
    'src/components/ts-style-elevation.js',
    'src/components/ts-style-form.js',
    'src/components/ts-style-grid.js',
    'src/components/ts-style-homepage.js',
    'src/components/ts-style-input.js',
    'src/components/ts-style-layout.js',
    'src/components/ts-style-products.js',
    'src/components/ts-style-select.js',
    'src/components/ts-style-shared.js',
    'src/components/ts-style-table.js',
    'src/components/ts-style-textarea.js',
    'src/components/ts-style-theme.js',
    'src/components/ts-style-typography.js',
    'src/components/ts-style-wp.js',
    'src/components/ts-view404.js',
    'images/manifest/icon-48x48.png',
    'images/manifest/icon-72x72.png',
    'images/manifest/icon-96x96.png',
    'images/manifest/icon-144x144.png',
    'images/manifest/icon-192x192.png',
    'images/manifest/icon-512x512.png',
  ],
  navigateFallback: '/index.html',
  navigateFallbackWhitelist: [/^(?!.*\.html).*/],
  navigateFallbackBlacklist: [/xml/],
  ignoreURLParametersMatching: [/^utm_/],
  runtimeCaching: [
    {
      urlPattern: /.*\?static\=true/,
      handler: 'NetworkOnly',
    },
    {
      urlPattern: /\.(?:js|css)$/,
      handler: 'StaleWhileRevalidate',
      options: {
        cacheName: 'static-cache',
        expiration: {
          maxEntries: 200,
        },
      },
    },
    {
      urlPattern: /\.(?:png|gif|jpg|jpeg|svg)$/,
      handler: 'CacheFirst',
      options: {
        cacheName: 'img-cache',
        expiration: {
          maxEntries: 200,
        },
      },
    },
    {
      urlPattern: /\.(?:json)$/,
      handler: 'NetworkFirst',
      options: {
        networkTimeoutSeconds: 3,
        cacheName: 'data-cache',
        expiration: {
          maxEntries: 200,
        },
      },
    },
    {
      urlPattern: /^https:\/\/storage.googleapis\.com/,
      handler: 'CacheFirst',
      options: {
        cacheName: 'cdn-cache',
        expiration: {
          maxEntries: 200,
        },
      },
    },
  ],
};